---
title: "長庚大學 大數據分析方法 作業六"
output: github_document
---

資管四甲  B0244143  張芳瑀
## 分析議題背景

現代科技進步，但每天還是有許多人死去，不管男女老少，因各種原因沒了生命，藉由統計的數據去做分析。

## 分析動機

科技日新月異，醫療設備、技術也跟著進步，在這21世紀當中，看似每個人都應該活得長壽健康，但卻不是每個人都如此，還是有人死於病痛或者其他原因，想藉由這份資料來探討分析。

## 使用資料
政府資料開放平台的死因統計，

載入使用資料們
```{r}
library(readxl)
library(readr)
#欄位說明
data.xls1<-read_excel("C:/Users/Fangyu/Desktop/全死因/col.xls",1)
View(data.xls1)
data.xls2<-read_excel("C:/Users/Fangyu/Desktop/全死因/col.xls",2)
View(data.xls2)
data.xls3<-read_excel("C:/Users/Fangyu/Desktop/全死因/col.xls",3)
View(data.xls3)
data.xls4<-read_excel("C:/Users/Fangyu/Desktop/全死因/col.xls",4)
View(data.xls4)
data.xls5<-read_excel("C:/Users/Fangyu/Desktop/全死因/col.xls",5)
View(data.xls5)


#各年死因統計
data1<-read_csv("C:/Users/Fangyu/Desktop/全死因/dead100.csv")
View(data1)
data2<-read_csv("C:/Users/Fangyu/Desktop/全死因/dead101.csv")
View(data2)
data3<-read_csv("C:/Users/Fangyu/Desktop/全死因/dead102.csv")
View(data3)
data4<-read_csv("C:/Users/Fangyu/Desktop/全死因/dead103.csv")
View(data4)
data5<-read_csv("C:/Users/Fangyu/Desktop/全死因/dead104.csv")
View(data5)

```

## 資料處理與清洗
1.判斷資料型別2.將有NA的資料移除

處理資料
```{r}
class(data.xls1)
class(data.xls2)
class(data.xls3)
class(data.xls4)
class(data.xls5)
class(data1)
class(data2)
class(data3)
class(data4)
class(data5)


data1<-data1[complete.cases(data1),]
data2<-data2[complete.cases(data2),]
data3<-data3[complete.cases(data3),]
data4<-data4[complete.cases(data4),]
data5<-data5[complete.cases(data5),]

```

## 探索式資料分析
由圖可知病因06為104年全台主要死因，再參考對照表得知06是惡性腫瘤。
```{r}
library(data.table)
data104<-data.table(data5)
data104[,.(Number=sum(N)),by=cause]

library(ggplot2)
ggplot(data104,
       aes(x= cause,
           y= N)) +
  geom_point()
```

## 期末專題分析規劃
期末專題要做死因跟年齡與性別的交叉分析
